
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      The target system is: Generic -  - arm
      The host system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: arm-none-eabi-gcc 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-Wall;-Wextra;-Wpedantic;-fdata-sections;-ffunction-sections;-O0;-g3
      Id flags:  
      
      The output was:
      1
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Build started 01.12.2024 16:23:17.
      Project "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(516,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
      LINK : fatal error LNK1181: nie mozna otworzyc pliku wejsciowego ,kernel32.lib" [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      Done Building Project "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(516,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
      
      "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: nie mozna otworzyc pliku wejsciowego ,kernel32.lib" [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:01.13
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: arm-none-eabi-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Build started 01.12.2024 16:23:18.
      Project "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(516,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
      LINK : fatal error LNK1181: nie mozna otworzyc pliku wejsciowego ,kernel32.lib" [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      Done Building Project "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(516,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
      
      "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: nie mozna otworzyc pliku wejsciowego ,kernel32.lib" [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.67
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      arm-none-eabi-gcc: fatal error: no input files
      compilation terminated.
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      arm-none-eabi-gcc: fatal error: no input files
      compilation terminated.
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-none-eabi-gcc.exe (GNU Tools for STM32 12.3.rel1.20240612-1315) 12.3.1 20230626
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: arm-none-eabi-gcc 
      Build flags: -mcpu=cortex-m4;-mfpu=fpv4-sp-d16;-mfloat-abi=hard;-Wall;-Wextra;-Wpedantic;-fdata-sections;-ffunction-sections;-O0;-g3
      Id flags:  
      
      The output was:
      1
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Build started 01.12.2024 16:23:30.
      Project "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(516,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
      LINK : fatal error LNK1181: nie mozna otworzyc pliku wejsciowego ,kernel32.lib" [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      Done Building Project "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(516,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
      
      "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: nie mozna otworzyc pliku wejsciowego ,kernel32.lib" [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.65
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: arm-none-eabi-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Build started 01.12.2024 16:23:31.
      Project "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
      C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(516,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
      LINK : fatal error LNK1181: nie mozna otworzyc pliku wejsciowego ,kernel32.lib" [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      Done Building Project "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (PrepareForBuild target) -> 
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Microsoft\\VC\\v170\\Microsoft.CppBuild.targets(516,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
      
      "D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (Link target) -> 
        LINK : fatal error LNK1181: nie mozna otworzyc pliku wejsciowego ,kernel32.lib" [D:\\praca\\projekty\\Home_sys\\Home_sys\\CMakeFiles\\3.31.0\\CompilerIdC\\CompilerIdC.vcxproj]
      
          1 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.64
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      arm-none-eabi-gcc: fatal error: no input files
      compilation terminated.
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:31 (enable_language)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      arm-none-eabi-gcc: fatal error: no input files
      compilation terminated.
...
